name: companion
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.1
  google_maps_flutter: ^2.1.1
  latlong2: ^0.9.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  flutter_onboarding_slider: ^1.0.11
  cupertino_icons: ^1.0.2
  google_fonts: any
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/